### ISSUE TITLE
Slow when typing into fields

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-editor#100]
The editor is slow when typing into fields. I suspect it can be improved debouncing the keys, because as of now `validate()` gets triggered more than necessary, but that's not the whole story.

I tried with a simple test: **15 keys** pressed in **~1sec**. The reference is my terminal emulator which has no input lag:

## Terminal
![terminal](https://user-images.githubusercontent.com/788293/68116466-3458ec00-fefb-11e9-904d-5eb1f15154cd.gif)
 
## Live site at https://publiccode-editor.developers.italia.it
![complete](https://user-images.githubusercontent.com/788293/68116511-4fc3f700-fefb-11e9-81b2-5ccd19cbe912.gif)

## Development with `validate()` disabled
![validate](https://user-images.githubusercontent.com/788293/68117782-98c97a80-fefe-11e9-8325-5d35c26f4b1f.gif)

## Development with `validate()` disabled and `rc-collapse` removed
![no-panels](https://user-images.githubusercontent.com/788293/68116574-784bf100-fefb-11e9-94f7-51245697cd4c.gif)

As you can see the slowest version is the deployed one, but my local version with `validate()` disabled (it just returns) is slow as well. I suspect `rc-collapse` (and possibly `redux-form`) is slowing things down, but my React-fu is not great.

Granted I'm using a CPU from 10 years ago, but it's noticeable even on newer ones.

**Comment by libremente** [comment]
Hi @bfabio and thanks for your issue!
We are aware of such an issue (I was discussing this with @sebbalex this morning, great timing! :)). I suspect redux-form may be a responsible but we need to dig further on this. I'll get back to you as soon as I have some reasonable answers. Thanks a lot! 👍

**Comment by bfabio** [comment]
@libremente You're welcome. Please let me know if you'd like me to run any tests with my crappy computer :)

**Comment by libremente** [comment]
@bfabio as you mentioned above, the issue is most probably happening due to the validate() call which happens after every insert. The next version of the validator (which uses a remote API for validation) will not suffer from this since it will trigger the validation just when the `submit` button is pressed. I leave this issue open as a reminder to check the performance of the next release @sebbalex

**Comment by libremente** [comment]
We need to check whether this is still happening with the new validation.

**Comment by bfabio** [comment]
@libremente there's still a slight input lag, but it's so much better now!

[This branch](https://github.com/bfabio/publiccode-editor/commits/debounce) puts the last nail in the coffin by debouncing the input fields. If you guys thinks it's worth it, I'll open a PR.
