### ISSUE TITLE
Remove pointer cursor from buttons in sidebar

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#126]
# Subject of the issue

Right now the sidebar buttons have a `cursor: pointer` that is misleading since the click on it does not trigger the click event. I'd remove the cursor or move the div inside the `a` tag if that's feasible. 

# Steps to reproduce

Move the cursor slightly below one of the three buttons "Copy / Upload / Download". The pointer cursor appears but the link is not underlined so it's not clickable. 

# Expected behaviour

The click event should be triggered.

**Comment by tikhsuP** [comment]
@libremente, I have made a PR #127 to solve this issue.
Please check.

**Comment by tikhsuP** [comment]
@libremente @sebbalex 
Is this issue still open?

**Comment by libremente** [comment]
Hi @tikhsuP, no, we can close this. Thank you!
