### ISSUE TITLE
Enhance the responsiveness of the sidebar

### ISSUE THREAD

**Issue by tikhsuP** [italia/publiccode-editor#128]
# Subject of the issue

The sidebar in the page [Publiccode-editor](https://publiccode-editor.developers.italia.it) isn't responsive.

# Steps to reproduce

Try opening the page in different screen sizes.

# Actual behaviour

### Anything around 840px:
![Screenshot (3)](https://user-images.githubusercontent.com/42881874/74657970-57ac5c00-51b7-11ea-96e8-dd8420fce13c.png)

### Anything between 840px - 640px:
![Screenshot (5)](https://user-images.githubusercontent.com/42881874/74658313-ffc22500-51b7-11ea-9c15-4f964d4d8f5f.png)

### Below 640px:
![Screenshot (7)](https://user-images.githubusercontent.com/42881874/74658315-02bd1580-51b8-11ea-9f0e-c8c48c342e20.png)

# Expected behaviour

The sidebar containing the COPY, UPLOAD and DELETE buttons must be made responsive to support different screen sizes.

**Comment by bfabio** [comment]
The refactor in `develop` got rid of the awkward sidebar, so this no longer applies.
