### ISSUE TITLE
RESET and GENERATE buttons breaking DOM

### ISSUE THREAD

**Issue by tikhsuP** [italia/publiccode-editor#129]
# Subject of the issue

The **Reset** and **Generate** buttons are breaking the desired DOM for screen sizes less then 580px.
The width of these buttons is fixed at 242px with a fixed gap of 80px between these buttons (i.e. left and right margins of 40px) irrespective of the screen size.
Clearly 40px+242px+80px+242px+40px = 644px exceeds the size of 580px.

# Steps to reproduce

Using developer options check the buttons for screen sizes less then 580px.

# Expected behavior

The button size should adjust according to the screen size.

This can be done by using a **responsive unit** like vw (viewport width) rather than a **fixed unit** like px (pixel(s)) in the class `editor_button` and removing the width attribute from the class `editor_button--custom`.

# Actual behaviour
### For screen sizes less than 580px:

![Screenshot (16)](https://user-images.githubusercontent.com/42881874/74749121-ad543780-528f-11ea-898e-bdc2bdc87f81.png)

### Swipe Left to see this:

![Screenshot (17)](https://user-images.githubusercontent.com/42881874/74749124-ae856480-528f-11ea-863c-87ea7e55b40b.png)

**Comment by libremente** [comment]
Hi @tikhsuP thanks for your effort! We will try to triage this isse soon and let you know.
