### ISSUE TITLE
Review Docker image creation and publication

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#130]
Opening an issue from the closed PR for better tracking and readability. 

Below the message from @bfabio:
--
@sebbalex No worries, that's great. I'll use that as my baseline.

I believe we can use [`envsubst`](https://linux.die.net/man/1/envsubst) with a JS template in place of `env.sh`:

```js
// appConfig.js.tpl
window.env = {
  ELASTIC_URL: "$PUBLICCODE_ELASTIC_URL",
  REPOSITORY: "$PUBLICCODE_REPOSITORY",
  VALIDATOR_URL: "$PUBLICCODE_VALIDATOR_URL",
}
```
and then at build:

```sh
$ envsubst '$PUBLICCODE_ELASTIC_URL,$PUBLICCODE_REPOSITORY,$PUBLICCODE_VALIDATOR_URL' < appConfig.js.tpl > config/appConfig.js
```

_Originally posted by @bfabio in https://github.com/italia/publiccode-editor/pull/111#issuecomment-600546821_

**Comment by libremente** [comment]
Involving also @LucaPrete in the discussion since he is helping to setup the new deployment strategy.

**Comment by LucaPrete** [comment]
@bfabio thanks for your review.

Please, keep in mind we're trying to build a single image, and give values to our variables at run-time instead.

Since the code runs at client-side, the only way we have to do this is to run a script as soon as the container starts, which changes the js that users will execute on their browsers.

Please, let me know if I misunderstood anything.

**Comment by bfabio** [comment]
@LucaPrete Sorry, I probably mislead you writing "at build" (as in "yarn build"). 

For docker images, I usually do something like this to set variables upon container start, using the entrypoint:

```bash
#!/bin/sh
#
# entrypoint.sh
#
set -e
 
# Optional check
[ -z "$PUBLICCODE_ELASTIC_URL" ] && (echo '$PUBLICCODE_ELASTIC_URL must be set' ; exit 1)
[ -z "$PUBLICCODE_REPOSITORY" ] && (echo '$PUBLICCODE_REPOSITORY must be set' ; exit 1)
[ -z "$PUBLICCODE_VALIDATOR_UR" ] && (echo '$PUBLICCODE_VALIDATOR_UR must be set' ; exit 1)
 
envsubst '$PUBLICCODE_ELASTIC_URL,$PUBLICCODE_REPOSITORY,$PUBLICCODE_VALIDATOR_URL' < appConfig.js.tpl > config/appConfig.js
 
exec "$@"
```

**Comment by LucaPrete** [comment]
Fabio, thanks.

Seems a good approach. The only advantage I see in our methodology is the
ability to do not have to hardcore var names in the bash script..what do
you think? Do you see any specific disadvantage?

Thanks,

-Luca

Il giorno mer 18 mar 2020 alle 18:19 Fabio Bonelli <notifications@github.com>
ha scritto:

**Comment by LucaPrete** [comment]
Hardcode, of course...hell t9 😂

Il giorno mer 18 mar 2020 alle 21:02 Luca Prete <preteluca@gmail.com> ha
scritto:

**Comment by bfabio** [comment]
> Fabio, thanks. Seems a good approach. The only advantage I see in our methodology is the ability to do not have to hardcore var names in the bash script..what do you think? 

@LucaPrete you're right of course, but sometimes being explicit and "declaring" what variables are passed down may be beneficial. We would avoid the potential confusion of the variable rename (with or without the PUBLICCODE_ prefix)

Do you think this might be the case?

> Do you see any specific disadvantage?

The main disadvantage I see is having a custom bash script to maintain whose scope is not instantly clear. I think a well known one-liner would be more readable and pain free. And It may be just me, but the less bash scripting around (ant is pitfalls!) the better :grinning:

**Comment by LucaPrete** [comment]
Fabio, looks like a good point!

Having a PR from you would be great. Would you mind sending one over?

Thanks again,

-Luca

Il giorno gio 19 mar 2020 alle ore 14:14 Fabio Bonelli <
notifications@github.com> ha scritto:

**Comment by bfabio** [comment]
@LucaPrete Sure: #131

**Comment by LucaPrete** [comment]
Closing this issue, as it's already been addressed. Opening another issue for @bfabio changes.
