### ISSUE TITLE
Blank page when trying to validate a form after choosing a "License" in the drop-down menu

### ISSUE THREAD

**Issue by luciopileggi** [italia/publiccode-editor#133]
A blank page appear after clicking on the "Generate" button and all the values you entered in the form are lost. Looks like this error occurs only if you have chosen a value in the "License" drop-down menu.

Tested on Safari and Chrome on OSX, Firefox on Ubuntu GNU Linux.

# Steps to reproduce
- Compile the form with any value or no values at all;
- Choose a License in the drop-down menu;
- Click on the "Generate" button.

**Comment by libremente** [comment]
May be related to this https://github.com/italia/publiccode-editor/pull/118/files since it has been merged recently.

**Comment by sebbalex** [comment]
@libremente yes, it is indeed related. I will dig in

**Comment by libremente** [comment]
@luciopileggi issue fixed, thanks @sebbalex.
Let me know if we can close this one.

**Comment by luciopileggi** [comment]
Tested again, now it's working properly. You can close this one.
