### ISSUE TITLE
publiccode.yml version should not be selectable

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#14]
As of now, the editor prompts the user with the desired Publiccode.yml version, allowing a choice between "development" and "0.1". However, the editor will be always able to only generate a publiccode file according to the latest spec so there's no need for this field.

The form field should be removed and the publiccode.yml version should be written statically somewhere in the interface, along with a link to the docs.

**Comment by sebbalex** [comment]
Closed by commit 3f54cb2

**Comment by sebbalex** [comment]
Closed by commit c64178e
