### ISSUE TITLE
Date picker is not rendered on Safari

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#15]
Date fields like "Release Date" do not enforce or suggest any particular format (for example YYYY-MM-DD) and there's no date picker. We should at least suggest the format.

**Comment by libremente** [comment]
I can see the date picker, however the only format recognized is the YYYY-MM-DD see https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/schema.html#data

**Comment by alranel** [comment]
After further checks, I realized that this issue is only specific to Safari, where the placeholders and the picker are not rendered.

Safari:
![screen shot 2019-03-04 at 18 11 53](https://user-images.githubusercontent.com/594957/53750063-20ab4080-3ea9-11e9-9687-d95295e4a20c.png)

Firefox:
![screen shot 2019-03-04 at 18 12 04](https://user-images.githubusercontent.com/594957/53750072-256ff480-3ea9-11e9-992b-bbdc131ca2ed.png)

We should probably change the input field to show the date in YYYY-MM-DD format, but the current behavior is fine.

I'm moving this issue to 1.1 and renaming it.

**Comment by sebbalex** [comment]
Seems we have a problem with this component.
Safari is still not supported (even in latest version). Format pattern follows browser language
and normalized after input, there is no API to change placeholder at the moment.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

We should consider to move to another one.

**Comment by libremente** [comment]
Weird, I'd go with the https://jqueryui.com/datepicker.
JQuery is already loaded, jquery UI not but I guess that would not be too much of a hassle including it. What do you think @sebbalex? At least we ensure that it is supported by all the major browsers https://jqueryui.com/browser-support/

**Comment by sebbalex** [comment]
@libremente I would go for https://jquense.github.io/react-widgets/api/DateTimePicker/
as we already have in our dependency and we're actually using it for other components.
It should cover as well all major browsers, what do you think?

**Comment by libremente** [comment]
@sebbalex If that's supported by all browser then great, go for it! :+1:
