### ISSUE TITLE
Use dropdown menus for countries and languages

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#16]
Fields like `countries` that expect a list of ISO 3166-1 alpha-2 country codes should have a dropdown menu instead of a free text field, because our parser/crawler performs strict validation on those values.

**Comment by libremente** [comment]
This is true also for keys like `availableLanguages` in the `Country Specific` section.

**Comment by alranel** [comment]
* `countries` are provided by ISO 3166-1 alpha-2 
* languages are provided by BCP47

**Comment by sebbalex** [comment]
Acknowledged by commit 0b5a1cb and 771f9f0.
