### ISSUE TITLE
The editor requires to have a branch called 'master'

### ISSUE THREAD

**Issue by evilaliv3** [italia/publiccode-editor#165]
It seems to me that currently files like loogos are searched by the editor in the master branch while performing the validation.

Actually many project could be using on other branch names.

e.g. in the context of globaleaks for example our main branch is called 'main'' as we do not use the slang 'master' condemning any use of coding terms deemed as oppressive metaphors or racially inappropriate (https://tools.ietf.org/html/draft-knodel-terminology-03)

We would appreciate if you could fix this and enable users to use an alternative name. Thank you!

![Screenshot_2020-07-24_17-54-04](https://user-images.githubusercontent.com/217034/88410439-aef1d080-cdd6-11ea-9dfc-fb83998b60d9.png)

**Comment by bfabio** [comment]
Related to https://github.com/italia/publiccode.yml/issues/35

**Comment by libremente** [comment]
Broken link @bfabio
