### ISSUE TITLE
longDescription should not generate HTML

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#17]
As of now, HTML markup is generated for the `longDescription` field, such as `<p></p>` tags and so on. The publiccode.yml spec allows Markdown and we should stick to it.

**Comment by libremente** [comment]
Should this be linked to https://github.com/italia/publiccode.yml/issues/8 ? Since it's a boolean, let's change it to a true bool...

**Comment by sebbalex** [comment]
Closed by commit 7764440
