### ISSUE TITLE
category selector is filtering too much

### ISSUE THREAD

**Issue by tassoman** [italia/publiccode-editor#184]
I was looking for categories, inside the publiccode editor web page and I didn't found anything about _security_

# Steps to reproduce

1. open publiccode editor web interface
2. write *secur* inside category field

# Expected behaviour

You should find `it-security`

# Actual behaviour

None found
![Istantanea_2020-12-09_16-08-55](https://user-images.githubusercontent.com/92727/101653676-dd97dd00-3a3f-11eb-834d-fec4e1a73dee.png)

**Comment by giosce** [comment]
I think there are a few drop-downs where the list of values is not relevant for everyone. I think that we should discuss a way for different organizations to have different lists.
I'm experimenting to call external API from my organization taxonomy, it works fairly simply. I'll work on making it more configurable.

**Comment by tassoman** [comment]
Fix didn't worked. Filtering still involve liteally all the tag (you must digit `it-secu` for filtering) not enough at UX.
What is mean by this issues is such as [Chosen](https://harvesthq.github.io/chosen/) behaviour. You can find something by digiting `kingdom`

**Comment by bfabio** [comment]
Hi @tassoman, we are working on a complete refactoring and fixing the issues directly there in the `develop` branch.

You can check out the preview here https://publiccode-editor-develop.vercel.app/ (always up to date with `develop`). Beware it's not functional yet, but this particular issue is fixed.

**Comment by tassoman** [comment]
Verificato funzionante, grazie!
