### ISSUE TITLE
Change it/riuso/ecosistemi to it/ecosistemi

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#20]
The publiccode spec was ambiguous about `it/riuso/ecosistemi` vs `it/ecosistemi`. The second is correct, so this editor should be changed.

**Comment by libremente** [comment]
Fixed in https://github.com/italia/publiccode.yml/blob/7464845b7842d101efdfc392bd2c41bc48bdd09d/docs/it/schema.it.rst#chiave-ecosistemi , now the editor  has to reflect this change

**Comment by sebbalex** [comment]
Closed by commit 9d99d17
