### ISSUE TITLE
Unfinished sentence

### ISSUE THREAD

**Issue by bzg** [italia/publiccode-editor#235]
https://github.com/italia/publiccode-editor/blob/master/src/app/contents/fields/generic.js#L447 contains a sentence that does not end correctly: "as mandated by the."

**Comment by libremente** [comment]
cc @sebbalex

**Comment by sebbalex** [comment]
Hello @bzg, surely we have a problem there and it'll be fixed soon, thanks for catching.
By the way, the sense of that was:

> ...The primary language subtag cannot be omitted, as mandated by the [BCP 47](https://tools.ietf.org/html/bcp47).

See [here](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/schema.core.html#section-localisation) (under 1.1.23.2) for full description.
Thanks

**Comment by bzg** [comment]
Well noted, thanks, and [fixed](https://github.com/etalab/publiccode-editor/pull/3/commits/5829f1def18155d2747a9364a1ff50c1935d7573) on our side.

**Comment by bfabio** [comment]
Fixed in `develop` as well (833e997f0b6eb392c50ec3f3ed607f630d2183c8).

The editor should take care of producing the proper tags, while the user sees just a combo box with the languages to pick, so there's no point of keeping that remark.
