### ISSUE TITLE
Remove link to undefined for prod

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#25]
Update the "Need help?" link that now points `undefined`. Should be coherent with the other portals.

**Comment by libremente** [comment]
Should this link to the slack channel? @alranel what do you suggest?

**Comment by libremente** [comment]
This should link to https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/  @sebbalex

**Comment by sebbalex** [comment]
Thanks for suggestion @libremente , fixed.
