### ISSUE TITLE
Translation in Italian

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#26]
Since most of the users (in the first place) will be Italians, it should be better to have an Italian interface by default with a switcher to Eng.

**Comment by alranel** [comment]
We just discussed this and since we cannot implement a switch right now, we can stick to English and translate the things that are still in Italian. We should also link both the English and the Italian docs for publiccode.yml on docs.italia.it

**Comment by expobrain** [comment]
@alranel I can help on this, is there any single file which contains all the lexemes or are they sparse into multiple files?

**Comment by libremente** [comment]
> @alranel I can help on this, is there any single file which contains all the lexemes or are they sparse into multiple files?

Hi @expobrain and thanks for the interest! As of now, there is not an immediate way to translate those strings. However, if you come up with a possibility, feel free to share it here (or, even better, propose a PR 👍). Thanks!

**Comment by bfabio** [comment]
What about using the client's `Accept-Language` instead of an in-content switch?
