### ISSUE TITLE
Localization Ready wrongly marked as required

### ISSUE THREAD

**Issue by Ainali** [italia/publiccode-editor#264]
# Subject of the issue

In section 7. Purpose & Audience, the checkbox Localization Ready is marked with a `*` indicating it is required. Not only does it not make sense to have it be required, it also generates fine with it not being checked.

# Steps to reproduce

Check the section 7. Purpose & Audience

# Expected behaviour

The field should not be marked as required.

# Actual behaviour

It is marked as required.

**Comment by bfabio** [comment]
Thanks @Ainali, confirming the issue
