### ISSUE TITLE
Use the Go parser for full validation

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#32]
The [Go parser](https://github.com/italia/publiccode-parser-go) used by the crawler performs stricter validation than this editor as it's not only syntactic but also semantic (i.e. it checks that images exist in the repo etc.)

So, as of now, a publiccode.yml file generated and validated by the editor might be discarded by the crawler. This would confuse users as the editor should guarantee that the software will be in the catalog.

We have two options:
1. reimplement the semantic validation logic in Javascript;
   * pros: editor remains client-side; we can provide better feedback for long operations (like downloading images)
   * cons: duplication of the validation logic; some validations might not work due to CORS (check)
2. wrap the Go parser in a web server that accepts a publiccode.yml file and a repo URL, and returns an array with errors (this AJAX validation can then be added to the editor to be executed only if the client-side validation succeeds)
   * pros: quicker to do, no code duplication
   * cons: editor will not be client-side anymore

**Comment by bfabio** [comment]
I wonder if compiling the parser to WASM would be viable, if so it could be the best of both worlds.

**Comment by sebbalex** [comment]
> I wonder if compiling the parser to WASM would be viable, if so it could be the best of both worlds.

@bfabio sounds interesting, I did not dig in deep with it but could worth think about it

**Comment by libremente** [comment]
Opened #124 , closing this one.
