### ISSUE TITLE
Proposal: migrating JSON schema to newer draft

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#35]
JSON Schema migration proposal from Draft-04 to Draft-07. 
See this for migration hints [https://json-schema.org/specification.html#migrating-from-older-drafts](https://json-schema.org/specification.html#migrating-from-older-drafts)

**Comment by alranel** [comment]
Update: @libremente is working on this.
The editor shall be updated to use the new JSON schema.

**Comment by libremente** [comment]
@alranel I don't think this strictly needed for 1.0. I'd move it to another release since I'm afraid creating a proper JSON schema tackling all the tests and stuff will require some further work and I don't want to block 1.0.

**Comment by sebbalex** [comment]
@libremente since we moved toward another solution, implementing the external validator this issue doesn't have to exist anymore, thoughts?

**Comment by bfabio** [comment]
Closing as obsolete.
