### ISSUE TITLE
Use BCP 47 for language tags intead of the three-letter ISO code

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#38]
As of now the editor generates three-letter language codes as sub-keys of `description/`, according to [publiccode.yml 0.1](https://github.com/italia/publiccode.yml/tree/0.1).

We're switching to BCP 47 in 0.2, so we need to update the editor accordingly.

**Comment by sebbalex** [comment]
Closed by commit 9d1a3a4
