### ISSUE TITLE
Long description field style on Chrome

### ISSUE THREAD

**Issue by sebbalex** [italia/publiccode-editor#39]
Long description field has a wrong height in Chrome browser

**Comment by sebbalex** [comment]
<img width="975" alt="screenshot 2019-03-01 at 18 08 49" src="https://user-images.githubusercontent.com/11008116/53654201-6ec40800-3c4d-11e9-9279-41044a70c98d.png">

no space for textarea below the widget.

**Comment by souravpd** [comment]
Hello ,
I have added an over-flow property to the editor content that seems to fix the issue
Please have a look at my Pull request [here](https://github.com/italia/publiccode-editor/pull/41)
Suggestions Appreciated 
Thankyou

**Comment by libremente** [comment]
Removing my local `package-lock.json` then running npm install again solved the issue for me (FF/Chrome). With yarn the problem does not show up. I would not waste time investigating into this issue for now. I'd remove this from 1.0 since we have other priorities ATM if that's ok for you @sebbalex

**Comment by sebbalex** [comment]
Yes sure, totally agree.

**Comment by libremente** [comment]
Fix by https://github.com/italia/publiccode-editor/commit/76c7122f1aede85c964fa3028e3f101bde8835ab , closing.
