### ISSUE TITLE
Upload from URL not working 

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#42]
# Subject of the issue

Uploading a `publiccode.yml` file through a valid URL ends with a JS popup saying:   
`error parsing remote yaml`
# Steps to reproduce

Upload a valid publiccode, such as:
https://raw.githubusercontent.com/italia/publiccode.yml/master/docs/en/example/publiccode.yml

# Expected behaviour

Load it correctly.
If a failure happen, provide a better error message to the users. 

# Actual behaviour
The file is not uploaded and an error message is fired.

**Comment by libremente** [comment]
@sebbalex I think for 1.0 we should disable/hide the upload button and then we can solve this issue in 1.1. What do you think?

**Comment by sebbalex** [comment]
Agree, we will examine the issue later on 1.1 Milestone.

**Comment by alranel** [comment]
I suggest we hide the entire `<div>` and not just disable the load button.

**Comment by sebbalex** [comment]
Closed by commit dbfc17f
