### ISSUE TITLE
License should be a dropdown rather than a text input

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#44]
`legal/license` should limit input to valid SPDX licenses, as required by https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/schema.html#sezione-legal
so we should use a dropdown list instead of a free text input.

Moreover, we should put the following at the top of the list as they are recommended by the [guidelines](https://docs.italia.it/AgID/linee-guida-riuso-software/lg-acquisizione-e-riuso-software-per-pa-docs/it/bozza/riuso-software/licenze-aperte-e-scelta-di-una-licenza.html#scelta-di-una-licenza):

* `EUPL-1.2`
* `AGPL-3.0-or-later`
* `BSD-3-Clause`
* `CC-BY-4.0`

**Comment by sebbalex** [comment]
Closed by commit 23e5689
