### ISSUE TITLE
Use yes/no instead of true/false for boolean keys

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#48]
As discussed in https://github.com/italia/publiccode.yml/issues/8, we should use the literals `yes` and `no` values for boolean values instead of `true` and `false`, since they are supported by the YAML spec:

>  A Boolean represents a true/false value. Booleans are formatted as English words (“true”/“false”,
>  “yes”/“no” or “on”/“off”) for readability and may be abbreviated as a single character “y”/“n” or “Y”/“N”.
 
source: https://yaml.org/type/bool.html

We should probably check whether the YAML library we use for serialization supports this.

**Comment by sebbalex** [comment]
YAML 1.2 has deprecated bool type y/n/yes/no/on/off. [spec](https://yaml.org/spec/1.2/spec.html#id2803629)
Only true and false are valid bool type.
@alranel @libremente We should close this issue.
