### ISSUE TITLE
master is currently broken on Safari 11

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#49]
The application is quickly rendered and then turns to a white screen. The console reports that `flatmap()` is not supported, and not surprisingly it's only supported [since Safari 12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap).

According to the [design guidelines](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/user-interface/lo-sviluppo-di-un-interfaccia-e-i-web-kit.html?highlight=explorer) we should support at least Safari 11+.

**Comment by francescozaia** [comment]
FYI, flatmap sembra [non essere supportato neanche da Edge](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap). Vi ricordo che possiamo usare BrowserStack per testare i nostri siti.

**Comment by sebbalex** [comment]
@francescozaia we were thinking the same thing at the same time. We can discuss on this purpose very soon. Thanks!
