### ISSUE TITLE
Reorganize fields

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#55]
We should review the fields and make sure the follow a logical order and grouping criteria.

For instance, `availableLanguages` and `localisationReady` should not be listed under country-specific because they are not country-specific.

**Comment by libremente** [comment]
Section 1
-> Move `landingURL` 

Section 2
-> Move `releaseDate` next to `softwareVersion`
-> Dev Status: remove description `Allowed values: concept, development, beta, stable, obsolete`
-> Software Type: remove description `Allowed values: standalone, addon, library, configurationFiles`
-> Move `categories` here
-> Move `localisationReady` 
-> Move `availableLanguages`

@sebbalex

**Comment by alranel** [comment]
* Name
   * name, applicationSuite, genericName, localizedName
* Repository & Documentation
   * URL, landingURL, roadmap, documentation, apiDocumentation
* Software Details
   * version, developmentStatus, releaseDate, softwareType, inputTypes, outputTypes, isBasedOn, dependsOn
* Legal & Reuse
   * license, authors, repoOwner, mainCopyrightOwner, codiceIPA, usedBy, awards
* Description & Features
   * description, shortDescription, features, localizationReady, availableLanguages, it/piattaforme, it/conforme
* Logo & Screenshots
   * logo, monochromeLogo, screenshots, videos
* Purpose & Audience
   * scope, category, countries, unsupportedCountries
* Maintainance
   * ...

**Comment by sebbalex** [comment]
Closed by e71ab14
