### ISSUE TITLE
The editor prints a <200b> at the end of the longDescription field

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#56]
# Subject of the issue

The editor prints a <200b> at the end of the `longDescription` field (in the resulting publiccode.yml file).
It happened me twice.

I will investigate further how to correctly reproduce this.

**Comment by libremente** [comment]
What should we do with this issue? @sebbalex

**Comment by sebbalex** [comment]
@libremente this should be fixed now, can you confirm?

**Comment by bfabio** [comment]
Can't reproduce, feel free to reopen this
