### ISSUE TITLE
Validate file extensions for logo

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#57]
The publiccode.yml spec restricts the accepted file extensions for images. For logo and monochromeLogo, .jpg is not accepted because we want images with transparent background. The editor should validate extensions.

**Comment by sebbalex** [comment]
As for:
`Raster file formats that support transparency include GIF, PNG, BMP, TIFF, and JPEG 2000, through either a transparent color or an alpha channel.`

Specified here: [Transparency (graphic)](https://en.wikipedia.org/wiki/Transparency_(graphic)), editor should allow only those extensions.
