### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by gtico80** [italia/publiccode-editor#61]
# Subject of the issue
Npm install gives an error instead of installing packages. According to package.json definition version number must be parsable by node-semver.

# Steps to reproduce
Execute npm install on the console.

# Expected behaviour

Npm install must restore packages

# Actual behaviour

$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid version: "1.1"
npm WARN publiccode-editor No description
npm WARN publiccode-editor No repository field.
npm WARN publiccode-editor No README data
npm WARN publiccode-editor No license field.

Node v10.13.0

**Comment by gtico80** [comment]
Pull request #62

**Comment by libremente** [comment]
Thanks for the PR @gtico80. Merged now, let's switch to semantic versioning as it should be. :+1:
