### ISSUE TITLE
Text search on license field does not work

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#63]
The text search in the license list (Legal > License) is not working. Typing some keys in that field 
triggers the opening of the dropdown box but the text inserted is not searched. 
![Schermata da 2019-05-13 13-03-17](https://user-images.githubusercontent.com/25111463/57616876-9bff3180-757f-11e9-8cc6-552907798f0b.png)

**Comment by sebbalex** [comment]
Closed by commit 40be29c
