### ISSUE TITLE
Crash when malformed date is inserted

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#65]
# Subject of the issue

The app crashes when a malformed date is inserted

# Steps to reproduce

1. Manually insert a date in the input box, something like `01/01/2000`. 
2. Click in the :calendar: icon next to the input box
3. A white page appears  and the CPU goes 100%.

The log grabbed from the console says:
```
TypeError: e is undefined
Error: E_INVALID_PAR_TYPE: Invalid `options` parameter (undefined). Plain Object expected.
```

# Expected behaviour

The malformed date should be ported into a good shaped one.

# Actual behaviour

It breaks the navigation, major bug.
GNU/Linux, FF 66.0.3

**Comment by libremente** [comment]
Seems to be working now with a newer FF version (68.0.1). I'd add a new label and give it a lower priority for the moment.

**Comment by libremente** [comment]
Still present (issue seen on FF 68.0.2). Same behavior.

**Comment by bfabio** [comment]
I didn't manage to reproduce it with `01/01/2000`, but when I used a date like `32/32/2000` (typed in or pasted, it doesn't matter), clicked outside the textbox and then clicked the calendar icon, it crashes 100% of the times.

Tested with both Firefox Nightly 72.0a1 and Chromium 78.0.3904.97 on Debian.
