### ISSUE TITLE
When uploading an invalid publiccode.yml there's no feedback about where the errors are

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#68]
When uploading an invalid publiccode.yml the editor says there's an error but does not tell the user where the error is, so they have to open all the accordion sections manually until they find fields with errors.

**Comment by sebbalex** [comment]
Since some fields were not rendered at upload time (lazy configuration for accordion) they were not validated as well. [forceRender](https://github.com/react-component/collapse) prop is enabled
