### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#7]
When adding several languages, the language loader goes out of scope and there is no horizontal scroll bar to reach it.

**Comment by souravpd** [comment]
Hello ,
I have added a flex-flow property this seems to correct this issue 
please have a look at this pull request [here](https://github.com/italia/publiccode-editor/pull/41)
Suggestions Appreciated

**Comment by libremente** [comment]
Fixed by #41, closing.
