### ISSUE TITLE
Null file generated on empty editor

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#8]
## The problem

> A file of 4 bytes containing the `null` word is generated

### What are the steps to reproduce this issue?

With the empty editor, click the `download` button. 

### Expected Results

> A message saying there is nothing to download. Or maybe the `download` button could be disabled if the editor is empty.

### Actual Results

> When the editor is empty, clicking the `download` button generates a `publiccode.yml` file of 4 bytes containing the `null` word.

**Comment by gtico80** [comment]
PR #36

**Comment by libremente** [comment]
#36 disables the download button when the editor is empty. I'm declaring this issue solved, thanks @gtico80 :+1:
