### ISSUE TITLE
Adding malformed field to publiccode breaks the editor

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#86]
# Subject of the issue

Adding Adding malformed field to publiccode breaks the editor.

# Steps to reproduce

Add a custom key/value pair to the publiccode locally then upload it to the editor.

# Expected behaviour

An error should popup.

# Actual behaviour

White page with `TypeError: (intermediate value)(...) is undefined` thrown in the console.

**Comment by bfabio** [comment]
Confirming.

WSD with `TypeError: can't access property "find", e is undefined` in console. No call is performed to the validator.

**Comment by bfabio** [comment]
Actually it looks like this is gone from master.
