### ISSUE TITLE
Generate button naming issue

### ISSUE THREAD

**Issue by libremente** [italia/publiccode-editor#9]
When a `publiccode.yml` file has been uploaded, the `generate` button does not change. 
It should be called `validate` or at least it could be possible to have a `generate / validate` button. If not, it is misleading for the user. 
This issue may be included in https://github.com/italia/publiccode-editor/issues/5

**Comment by gtico80** [comment]
Pull request #43

**Comment by libremente** [comment]
PR Merged, issue closed, thank you for your contribution! :+1:
