### ISSUE TITLE
Long lines in the "Long description" make the left pane grow

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-editor#98]
# Steps to reproduce

Input a long line in the "Long Description" field.

![publiccode-editor-long-description](https://user-images.githubusercontent.com/788293/68069486-d1cbe880-fd60-11e9-9730-5a90c923c46f.gif)

Sorry for the low quality GIF, Github doesn't allow WEBM.

# Expected behaviour

The textarea should wrap the text

# Actual behaviour

The left pane gets bigger and bigger, hiding the YAML pane.

**Comment by libremente** [comment]
Hi @bfabio, yes this is definitely a bug. That pane has to have a fixed length.

**Comment by sebbalex** [comment]
Closed by #105
